version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/"
    schema: "schema/"
    gen:
      go:
        package: "db"
        out: "../db"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
        omit_unused_structs: true

        # overrides:
        #   - db_type: "pg_catalog.varchar"
        #     go_type: "database/sql.NullString"
        #     nullable: true
