version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/"
    schema: "../../../../../migrations/postgres"
    gen:
      go:
        package: "db"
        out: "../db"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
        overrides:
          # if it's type of schema, add pg_catalog.* prefix
          # if it's type which get from queries, just use itseft
          - db_type: "timestamptz"
            nullable: true
            go_type: "database/sql.NullTime"

          - db_type: "timestamptz"
            nullable: false
            go_type: "time.Time"

          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"

          - db_type: "pg_catalog.varchar"
            nullable: true
            go_type: "database/sql.NullString"

          - db_type: "text"
            nullable: true
            go_type: "database/sql.NullString"

          - db_type: "pg_catalog.int4"
            nullable: true
            go_type: "database/sql.NullInt32"

          - db_type: "serial"
            nullable: true
            go_type: "int32"

          - db_type: "pg_catalog.numeric"
            nullable: true
            go_type: "github.com/shopspring/decimal.Decimal"

          - db_type: "pg_catalog.numeric"
            nullable: false
            go_type: "github.com/shopspring/decimal.Decimal"
