version: "2"
linters:
  default: all
  disable:
    - depguard
    - wsl
    - testpackage
    - tagliatelle
    - revive
    - wrapcheck
    - exhaustruct
    - varnamelen
    - tagalign
  settings:
    nlreturn:
      block-size: 2
