// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Attribute struct {
	ID int32 `json:"id"`
	// eg: color, size
	Name string `json:"name"`
}

type AttributeValue struct {
	ID          int32 `json:"id"`
	AttributeID int32 `json:"attribute_id"`
	// eg: red, blue, S, M
	Value string `json:"value"`
}

type Brand struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Cart struct {
	ID        int32        `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type CartItem struct {
	ID               int32     `json:"id"`
	CartID           int32     `json:"cart_id"`
	ProductVariantID int32     `json:"product_variant_id"`
	Quantity         int32     `json:"quantity"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Product struct {
	ID           int32           `json:"id"`
	Name         string          `json:"name"`
	Slug         string          `json:"slug"`
	Desciprtion  sql.NullString  `json:"desciprtion"`
	CategoryID   int32           `json:"category_id"`
	BrandID      int32           `json:"brand_id"`
	MainImageUrl sql.NullString  `json:"main_image_url"`
	BasePrice    decimal.Decimal `json:"base_price"`
}

type ProductVariant struct {
	ID            int32           `json:"id"`
	ProductID     int32           `json:"product_id"`
	Sku           string          `json:"sku"`
	Price         decimal.Decimal `json:"price"`
	StockQuantity int32           `json:"stock_quantity"`
	Sold          int32           `json:"sold"`
	ImageUrl      sql.NullString  `json:"image_url"`
	IsDefault     bool            `json:"is_default"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     sql.NullString `json:"username"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Role         string         `json:"role"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type VariantAttributeValue struct {
	VariantID int32 `json:"variant_id"`
	ValueID   int32 `json:"value_id"`
}
